### ISSUE TITLE
Table S11 results from Appendix of AutoGluon-Tabular article

### ISSUE THREAD

**Issue by pplonski** [Innixma/autogluon-benchmark#1]
I'm working on AutoML package [mljar-supervised](https://github.com/mljar/mljar-supervised) and I would like to compare my results with AutoGluon on OpenML datasets.

What metric is reported in Table S11 in appendix from AutoGluon-Tabular article? I can't find matching results in this repository. Could you please help me?

For example for dataset `Australian` (from table S11) there is loss reported 0.045 for Auto-WEKA. Is it logloss? Do you have results of Auto-WEKA in this repository? Where I can find them? And where I can find results for AutoGluon?

**Comment by Innixma** [comment]
Sorry for the confusion, this repo was from a very old version of the benchmark run prior to the paper that we had planned for a blog post but delayed in favor of the paper. I have updated this repo with warnings and links so hopefully no-one else gets confused.

Please see [this repo](https://github.com/Innixma/autogluon-benchmarking) for the full results + code.

Raw results are here: https://github.com/Innixma/autogluon-benchmarking/tree/master/data/results/input/raw

To generate all of the graphs and tables used in the paper directly from the raw files, run this file: https://github.com/Innixma/autogluon-benchmarking/blob/master/autogluon_utils/benchmarking/evaluation/runners/run_full.py

The table S11 shows the error in regards to the dataset's evaluation metric (1-AUC for binary, logloss for multiclass) using the first fold of each dataset. Note that for a more accurate comparison, you could average the error across all 10 folds. We used only the first because we were comparing with GCP and it was very expensive to do runs beyond the first fold with GCP.

Hope this helps! Let me know if it works for you.

**Comment by pplonski** [comment]
Perfect! :) Thank you for help!

**Comment by pplonski** [comment]
Last question ;) I assume that all methods (except GCP) are trained with 4 cores machines (m5.large)?

**Comment by Innixma** [comment]
No problem! We used m5.2xlarge for all OpenML datasets and all methods (except GCP), to keep consistent with the original AutoML Benchmark paper. m5.2xlarge are 4 core (8 thread) machines.
